apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  description: ${{ values.description | dump }}
  labels:
    - "knative.dev/func-template": "node-http"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
